sonar.projectKey=komorebi-cafe
sonar.projectName=Komorebi Café
sonar.sources=app/,scripts/,bin/
sonar.tests=tests/
sonar.php.coverage.reportPaths=tests/reports/coverage.xml
sonar.php.tests.reportPath=tests/reports/junit.xml
sonar.exclusions=vendor/**,public/vendor/**,storage/**
sonar.test.exclusions=tests/e2e/**
sonar.sourceEncoding=UTF-8
sonar.php.version=8.4
