[PHP]
expose_php = Off
date.timezone = Europe/Madrid
default_charset = UTF-8

[Session]
session.use_strict_mode = 1
session.cookie_httponly = 1
session.cookie_secure = 0
session.cookie_samesite = Lax
