[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info
user=root

[program:frankenphp]
command=frankenphp run --config=/app/frankenphp.Caddyfile
directory=/app
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=30
stopsignal=TERM

[program:queue_emails]
command=php /app/bin/email-worker.php
directory=/app
autostart=true
autorestart=true
startretries=3
numprocs=%(ENV_QUEUE_EMAILS_PROCS)s
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=60
stopsignal=TERM

[program:queue_notifications]
command=php /app/bin/notification-worker.php
directory=/app
autostart=true
autorestart=true
startretries=3
numprocs=%(ENV_QUEUE_NOTIFICATIONS_PROCS)s
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=60
stopsignal=TERM

[program:queue_default]
command=php /app/bin/worker.php default
directory=/app
autostart=true
autorestart=true
startretries=3
numprocs=%(ENV_QUEUE_DEFAULT_PROCS)s
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=60
stopsignal=TERM
